# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob.yaml

images:
  - name: etcd-backupper
    newName: registry.sighup.io/fury/dr/etcd-backup/etcd-backupper
    newTag: alpine3.21-v3.5.19
  - name: rclone
    newName: registry.sighup.io/fury/dr/etcd-backup/rclone
    newTag: v1.69-stable

configMapGenerator:
  - name: etcd-backup-pvc-config
    literals:
      - retention=10d
      - backup-prefix=my-pvc-etcd-backup-
  - name: etcd-backup-pvc-certificates-location
    literals:
      - ETCDCTL_CACERT=/etcd/etcd/ca.crt
      - ETCDCTL_CERT=/etcd/apiserver-etcd-client.crt
      - ETCDCTL_KEY=/etcd/apiserver-etcd-client.key
