# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
spec:
  template:
    spec:
      initContainers:
      - image: velero/velero-plugin-for-aws
        imagePullPolicy: Always
        name: velero-plugin
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /target
          name: plugins
      - name: wait-for-minio-setup
        image: groundnuty/k8s-wait-for
        imagePullPolicy: Always
        args: ["job", "$(MINIO_SETUP_JOB_NAME)"]
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
